// Generated by Wrangler on Sun Jun 02 2024 16:48:47 GMT+0930 (Australian Central Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	STATUS_PAGE: KVNamespace;
}
