#:schema node_modules/wrangler/config-schema.json
name = "status-page"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "STATUS_PAGE"
id = "6773564da4ac4a649febb15c781c5de2"
